### ISSUE TITLE
max pixels price is over 90EOS

### ISSUE THREAD

**Issue by StupidStudentInSchool** [eosasia/eospixels#3]
According the open source code，the max price of pixels never over 90Eos. Let me doubt the authenticity of the source code.

**Comment by StupidStudentInSchool** [comment]
I have written several articles, I hope you can help to correct.[https://bihu.com/article/1434909](url)

**Comment by dfguo** [comment]
Yes, this was originally implemented to limit the cap of each pixel as we didn't anticipate how popular the game would become. You could remove it. I believe the community launched versions have all removed this cap.

**Comment by StupidStudentInSchool** [comment]
@dfguo why didn't you upload new source . This will make the project more convincing.

**Comment by dfguo** [comment]
@StupidStudentInSchool we are not maintaining it anymore. Please see the annoucement: https://medium.com/@eosasia/eos-pixels-discontinued-source-code-released-77bd29d65beb

**Comment by StupidStudentInSchool** [comment]
@dfguo Can you provide web front-end code?
